FROM openjdk:8-jdk-alpine
RUN apk add python3
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
COPY . /app



CMD ["gunicorn", "--bind", "0.0.0.0:5001", "app:app"]
#CMD ["python3", "-u", "app.py"]